### ISSUE TITLE
Undim When Paused Feature Request

### ISSUE THREAD

**Issue by leejk421** [mpolednik/script.kodi.hue.ambilight#15]
When using the original version of this addon, I could set the light strip behind my tv to run in ambient light mode, and the other 2 lights above my couch to work like the current theater mode works, dimming when playback starts and undimming on pause. With the way it is now, it seems you can only have one mode or the other. Can that original behavior be brought back? It was really cool to have the light strip change colors, while the other two lights behaved in theater mode. I guess what's missing is to add the same undim on pause behavior to ambient light mode.

**Comment by Moyster** [comment]
@leejk421 Replying so you know someone saw that issue.

I think the plugin's maintainer (mpolednik) said a bit of rework was needed before implementing new features : 
https://github.com/mpolednik/script.kodi.hue.ambilight/issues/6

I'm not sure if anybody is currently working on it tho, I still have a couple weeks free before going back to school, I might throw an eye at what can be done ;) 
(/!\ disclaimer : It's not a promise tho and I have no powers here  /!\)

**Comment by mpolednik** [comment]
@leejk421 Replying late so you know even more people saw the issue.

I'm not sure if the previous combined mode was intentional or a bug, because AFAIK there is no change that directly broke it. That being said, I'll try to reserve some time to clean up the flows and see what could we do about it.

**Comment by mpolednik** [comment]
Version 1.0 now supports different groups of light all the tasks - use ambilight group for the strip and theater group for the other two lights.

**Comment by mpolednik** [comment]
Closing due to no feedback - if you still feel this bug is present, please re-open the issue.
