### ISSUE TITLE
Undim Brightness Incorrect

### ISSUE THREAD

**Issue by leejk421** [mpolednik/script.kodi.hue.ambilight#16]
Hi,

In ambient light mode when dimming a group of lights on movie playback, it seems that the undim brightness level is reset to the brightness level of the lights when KODI was started, rather than the brightness level of the lights before a movie is played.

**Comment by Moyster** [comment]
Can confirm the bug happens here as well.

**Comment by mpolednik** [comment]
Version 1.0 (now master) should now properly save the state each time before playback starts.

**Comment by mpolednik** [comment]
Closing due to no feedback - if you still feel this bug is present, please re-open the issue.
