### ISSUE TITLE
[TODO] Refactor: clean up a lot of the old code that's still in the addon, but not necessary

### ISSUE THREAD

**Issue by Moyster** [mpolednik/script.kodi.hue.ambilight#21]
Refactor: clean up a lot of the old code that's still in the addon, but not necessary

**Comment by H3lls7rik3r** [comment]
While checking the code I found several if statments with "useLegacyApi". In fact with Kodi v17 there is no longer the line 740 "getCaptureState()", so useLegacyApi will allways be "false".

**Comment by H3lls7rik3r** [comment]
yeah, that's something I could have thought about... makes sense. Thanks :)

**Comment by Moyster** [comment]
@mpolednik : hello, what's your thoughts on the legacyApi / getCaptureState trick, since kodi v17 is now "officially" stable, and v18 has started nightlies, should the legacyApi be removed ?
(ps: I think that's why some users on arm boxes were having troubles with the plugin... i think master branch is broken on v16)  
Same goes for the "ambilight old algo", I suppose this can go away too.  
  
Is it okay to push to the refactoring branch ?

**Comment by mpolednik** [comment]
@Moyster I believe it's being done in refactoring-v9-candidate branch (which happens to be rewrite of the core functionality). Currently, there are few issues with the branch but as soon as I get the previous behavior, I'll branch out v17 and move master to v17/v18 with the refactoring in place to *finally* get all the wishes in.

**Comment by Moyster** [comment]
@mpolednik : Hi, thanks for your answer.  
Well I just wanted to know, as this issue is about refactoring/cleaning-up old unnecessary code, if I could help you in anyway, ie. cleaning the LegacyApi ifdef or the old ambilight algo.  
The v9 branch was not moving so I assumed it would be a good time to sneak in a PR or two, but I asked first no to disturb your WIP. 

Cheers !
