### ISSUE TITLE
Problem with Kodi 17 Krypton

### ISSUE THREAD

**Issue by JesCR** [mpolednik/script.kodi.hue.ambilight#28]
Hi mpolednik!

i can't get this addon to work...

It works perfectly in kodi v16, but fails in v17 beta 3.
Here is the error:

"10:49:36 T:139821468374784 ERROR: EXCEPTION Thrown (PythonToCppException) : 
-->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: 
Error Contents: local variable 'i' referenced before assignment
Traceback (most recent call last):
File "/share/CACHEDEV1_DATA/.qpkg/mykodi17/homes/newkodi17/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 748,
in run()
File "/share/CACHEDEV1_DATA/.qpkg/mykodi17/homes/newkodi17/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 594, 
in run 
hsvRatios = screen.spectrum_hsv(screen.pixels, screen.capture_width, screen.capture_height)
File "/share/CACHEDEV1_DATA/.qpkg/mykodi17/homes/newkodi17/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 541, 
in spectrum_hsv
if int(i) != 0:
UnboundLocalError: local variable 'i' referenced before assignment
-->End of Python script error report<--
"

i'm running kodi in a QNAP Nas, throught the HDMI out...
Any Clue?`

**Comment by mpolednik** [comment]
Yeah, we're relying on quite ugly Python feature of leaving variable after the loop. On the other hand, looking at the code, it seems one of the PRs brought in quite ugly bug. Will investigate.

**Comment by mpolednik** [comment]
@JesCR can you try the plugin from "issue28" branch? https://github.com/mpolednik/script.kodi.hue.ambilight/tree/issue28

**Comment by JesCR** [comment]
Sure!!!
i'm at work now, give 6 hours to get home!

Thanks for your answer! :)

**Comment by JesCR** [comment]
Ok, first impressions with a light test (still daylight here)
Setup: Ambilight with two lights, all the rest as default, debug on.
First: No more Kodi Errors message!
-Play a movie: Left Light ok, right light dim to zero and never light up again.
-Stop, and lights the second with the philips hue app
-Play tv show, two lights off
-Stop and turn on the two lights with the philips hue app
-Play another movie: ok!
-Stop, lights go to "default" state
-Play a tv show: ok!

Tonight i will report if everything works properly :)

i left here the log file just in case...
[kodi.log.zip](https://github.com/mpolednik/script.kodi.hue.ambilight/files/533963/kodi.log.zip)

**Comment by VDRrulez** [comment]
Some days ago I've bought a hue bridge and a lightstrip. I'm running SPMC 16.4.2 on the Nvidia Shield TV. With this issue28-patch it is the first time that I get colors that match the colors on the tv screen.

**Comment by mpolednik** [comment]
It seems that the change should only improve things, merged it into master.
