### ISSUE TITLE
Theatre mode -- avoid when video screensaver is playing?

### ISSUE THREAD

**Issue by tremby** [mpolednik/script.kodi.hue.ambilight#31]
I'm using the [screensaver.atv4](https://github.com/enen92/screensaver.atv4) plugin for video screensavers. Problem is that they look to the Hue plugin like a regular video playing and so the lights dim when a screensaver starts. Can you think of any way around this?

[I asked also over on their tracker.](https://github.com/enen92/screensaver.atv4/issues/15)

**Comment by chris400** [comment]
There is already an option 'disable for short movies' - maybe this works for you?

**Comment by tremby** [comment]
Thanks, but no, I don't think so. Some of these screensaver videos are longer than short cartoons.

**Comment by Moyster** [comment]
@enen92 Hi !  
I was passing by, I don't really have much time to implement your changes, but you can submit pull requests, I'll give it a swirl and attempt to fix possible quirks ;)  
I won't talk in the name of @mpolednik , but I'm pretty sure he lacks the time as well to show some love to the plugin. The "roadblock" for publishing the add-on is a good ol' syntax check, repo owner stated unit tests aren't mandatory.  
  
Anyway, thanks for dropping by, don't hesitate to send me a mail as I don't track notifs here (ps: it's on my github profile ;) )

**Comment by mpolednik** [comment]
Hopefully fixed by #33 (which is based on top of #32 which should get me motivated enough to give the addon love it deserves). Will test later today.

**Comment by mpolednik** [comment]
Works according to my testing (which now includes lightstrip :3 ). Thanks for the easy way of detecting the screensaver!

**Comment by tremby** [comment]
Giving it a shot...

**Comment by tremby** [comment]
Confirmed working. Thanks to @enen92 and @mpolednik!
