### ISSUE TITLE
Cannot set light groups in Kodi 16. With Confluence skin

### ISSUE THREAD

**Issue by hstamas** [mpolednik/script.kodi.hue.ambilight#39]
Did a fresh Kodi install. Installed Kodi Hue. When going to do initial setup you cannot get into the light group sections.

**Comment by JesCR** [comment]
And you could "discover" the hue brigde? (i couldn't)
If you have a backup of the settings.xml you could try tu put in the userdata/addon_data directory

**Comment by hstamas** [comment]
Yes I am able to use the discover feature successfully. I just can't enter the screens to set the groups.

**Comment by mpolednik** [comment]
Are you trying master branch with kodi 16? That's not really supported (since the addon now uses v17 exclusive APIs).

**Comment by hstamas** [comment]
Yeah I am still using Kodi 16.1 as there are some issues with the widgets in 17 that I was hoping to avoid (not related to Kodi Hue). Will update tonight and report back.

**Comment by hstamas** [comment]
Yup. That was it. Kodi 17 only. Should this be documented somewhere?

**Comment by mpolednik** [comment]
Hmm it should, I thought it's in the README.

**Comment by Fofer** [comment]
It's not in the README.
