### ISSUE TITLE
figure out branching and versioning

### ISSUE THREAD

**Issue by mpolednik** [mpolednik/script.kodi.hue.ambilight#4]
This is mostly personal preference, but I prefer the branching to be as follows:

- master - current develop branch, should be default for PRs
- major branch (what about using same versioning as Kodi does? e.g. 16, 17...) - HEAD for minor forks
- minor fork (16.1, 16.2) - possibly not needed

According to personal experience, it makes sense to support newest Kodi + one version back.

**Comment by mpolednik** [comment]
The branching is now as follows:

master: v17+, possibly backwards compatible
v16: v16 obviously ;) can still be maintained for v16 users
old: the old code without ambilight improvements, mostly exists as a reference

**Comment by Moyster** [comment]
"old: the old code without ambilight improvements, mostly exists as a reference"
Is "old" supposed to be v16 compatible ? Because it currently ain't (cf 37be5253b76 )

**Comment by mpolednik** [comment]
It's not supposed to be anything compatible, I've merged the PR prematurely. Anyway, we should focus on master & v16 (that is supposed to be v16 compatible).
