### ISSUE TITLE
Ambilight don't work and Theater don't undimm in Android TV (Nvidia Shield)

### ISSUE THREAD

**Issue by JesCR** [mpolednik/script.kodi.hue.ambilight#44]
So when i force the hue_ip to avoid #37 the ambilight mode don't work.
When a playback starts the lights turn red and/or blue and never changes again.
The theater mode starts working, but when the playback pauses/stop don't undimm to previous state.
This is the onlye error i get:

```
> 11:52:41.204 T:138410161232   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'MyPlayer' object has no attribute 'playlistpos'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight/default.py", line 138, in onPlayBackEnded
                                                if self.playlistpos < self.playlistlen-1:
                                            AttributeError: 'MyPlayer' object has no attribute 'playlistpos'
                                            -->End of Python script error report<--
```

I try with SPMC (and branch v16), Kody17.0, Kody17.1 RC1 and always the same...

**Comment by JesCR** [comment]
Ok!
After a lot of web searching and tests i found a workaraound for the addon in a Nvidia Shield TV device (and i supposse every android tv device...)

**Go to System->Settings->Video
Be sure "Expert" mode is enable
Uncheck MediaCodec(surface) hardware acceleration**

Now the addon works again :)

**Comment by mpolednik** [comment]
Cool, seems like similar issue to the previous raspberry pi (hw video processing).

**Comment by sungolfer** [comment]
That fix worked for me too.

**Comment by JesCR** [comment]
ok. Closed!

**Comment by tfraley** [comment]
I can't seem to find this option in my Kodi. I'm runing on Nvidia switch as well. 
Have they moved the option or am I just not seeing it?

**Comment by JesCR** [comment]
Maybe your skin change the location?
Search in the video or playback settings... With the expert mode enable...

**Comment by tfraley** [comment]
Thank you for the reply. 
I found it, I was looking in the wrong location
It was under the player section.

Working well now
