### ISSUE TITLE
code styling updates

### ISSUE THREAD

**Issue by mpolednik** [mpolednik/script.kodi.hue.ambilight#5]
The code should be at least partially pep8 compliant - indentation is the biggest offender. Strict pep8 doesn't make sense as the main idea is to have fun. :)

**Comment by AnthraxLeprosyPi** [comment]
I already had my local code auto-beautified using pep8 - not that hard to do but pull request looked scary as hell so I cancelled it ;-)

Any reason why this hasn't been done already? Because of Forking/Merging issues?

**Comment by mpolednik** [comment]
More of a fear. We have no test coverage at all, changing anything just for the sake of stylistics is a dangerous task. I have tried autopep8, it seemed "mostly OK", but the danger is there.

**Comment by Moyster** [comment]
I guess this issue can be closed, as of :  
https://github.com/mpolednik/script.kodi.hue.ambilight/commit/5f9ffe566cb37f18ce48ee657feb6d0ce11c5f71  

Code refactoring is under another issue ( https://github.com/mpolednik/script.kodi.hue.ambilight/issues/21 )

**Comment by mpolednik** [comment]
Done in 1.0. Well, almost, I don't want to blindly do everything pep8ish.
