### ISSUE TITLE
No color change on fireTV in ambilight mode

### ISSUE THREAD

**Issue by jankete** [mpolednik/script.kodi.hue.ambilight#55]
Hi,

last weekend I got my Hue Starter-Set and for sure tried your addon on my 17.1 kodi on my fireTV (2nd Gen). I had no issues configuring the addon. The bridge was discovered and connected and I could choose the bulbs I want to use for ambilight fuction.

But when I start a video the only thing that happens is that my light goes green. There is no change of color 
or brightness during the playback. When I stop the film, the color goes back to what it was before.

What might be wrong here?

Regards,
Jankete

**Comment by JesCR** [comment]
Hi!
Try to disable the "hardware acceleration"
In the Nvidia Shield i have to uncheck "Mediacodec(surface)" to make the addon work...

**Comment by jankete** [comment]
Hi!
You say, that it won't work with hardware accelerated videos? So I might get other issues by deactivating hardware acceleration. :-/

**Comment by mpolednik** [comment]
@jankete That seems to be the case - if the video is not processed in a manner Kodi can see it, there is no way to do any image calculations.

**Comment by JesCR** [comment]
I think that the problem is with the Mediacodec(surface) or equivalents.
This method sends raw video to the graphics card and in that way the add on can't analyze it and get the necessary info (more or less :P). But with that option disable i don't have any issue, even with HEVC files...

**Comment by jankete** [comment]
OK. Thanks so far. I'll try later this day.

**Comment by jankete** [comment]
After deactivating "Mediacodec(Surface)", the addon works fine. No other issues in playback so far. Thanks for your support.

**Comment by deusxm** [comment]
You can also use the following fix to re-enable Surface for smooth acceleration Nd maintain Ambilight.

https://github.com/koying/SPMC/wiki/How-do-I-get-Hue,-boblight,-hyperion...-to-work-with-Mediacodec-Surface%3F
